In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("/Users/wech/Library/CloudStorage/OneDrive-UniversidaddelValledeGuatemala/UVG/12VO/Graduación/thesis/datasets/VHA.csv")

In [3]:
df.head(5)

,SKU,MMX_Q1,MMX_Q2,MMX_Q3,MMX_Q4,MMXVI_Q1,MMXVI_Q2,MMXVI_Q3,MMXVI_Q4,MMXVII_Q1,...,MMXX_Q2,MMXX_Q3,MMXX_Q4,MMXXI_Q1,MMXXI_Q2,MMXXI_Q3,MMXXI_Q4,MMXXII_Q1,MMXXII_Q2,MMXXII_Q3
0,1330350,104943.65,42790.81,41580.93,594000.10,573833.47,55058.18,17562.66,1460040.90,625137.64,...,89369.83,154390.57,1685219.22,1204945.74,551296.73,964839.95,2191868.69,1738016.33,531366.33,378666.51
1,1756500,151763.57,125249.26,133092.32,134435.47,139545.52,204142.58,190888.54,93335.78,116854.09,...,252277.21,126281.10,561785.40,327912.55,163029.42,280552.20,159786.95,0.00,326441.55,189307.39
2,1290175,147489.12,146853.68,180893.96,196218.15,195245.08,179370.76,234703.20,215143.05,113589.29,...,142056.38,159122.70,183445.17,218382.68,187876.87,226129.13,207475.02,281957.35,175005.33,131621.11
3,1754020,130814.67,95154.02,107642.10,95156.68,102794.75,112687.16,124126.11,76678.39,139169.00,...,88880.92,218994.17,279754.58,282162.43,145982.43,121073.63,223983.02,158112.35,183383.56,144306.64
4,150058,173477.36,135680.98,145588.89,95455.56,137334.41,142099.19,95684.62,27123.80,129096.72,...,104999.18,122677.51,114432.59,123469.05,113533.50,117861.71,118718.78,96527.73,114107.88,77118.15

In [4]:
df = df.drop('SKU', axis=1)

In [5]:
df

,MMX_Q1,MMX_Q2,MMX_Q3,MMX_Q4,MMXVI_Q1,MMXVI_Q2,MMXVI_Q3,MMXVI_Q4,MMXVII_Q1,MMXVII_Q2,...,MMXX_Q2,MMXX_Q3,MMXX_Q4,MMXXI_Q1,MMXXI_Q2,MMXXI_Q3,MMXXI_Q4,MMXXII_Q1,MMXXII_Q2,MMXXII_Q3
0,104943.65,42790.81,41580.93,594000.10,573833.47,55058.18,17562.66,1460040.90,625137.64,54557.95,...,89369.83,154390.57,1685219.22,1204945.74,551296.73,964839.95,2191868.69,1738016.33,531366.33,378666.51
1,151763.57,125249.26,133092.32,134435.47,139545.52,204142.58,190888.54,93335.78,116854.09,169941.25,...,252277.21,126281.10,561785.40,327912.55,163029.42,280552.20,159786.95,0.00,326441.55,189307.39
2,147489.12,146853.68,180893.96,196218.15,195245.08,179370.76,234703.20,215143.05,113589.29,155946.84,...,142056.38,159122.70,183445.17,218382.68,187876.87,226129.13,207475.02,281957.35,175005.33,131621.11
3,130814.67,95154.02,107642.10,95156.68,102794.75,112687.16,124126.11,76678.39,139169.00,139927.14,...,88880.92,218994.17,279754.58,282162.43,145982.43,121073.63,223983.02,158112.35,183383.56,144306.64
4,173477.36,135680.98,145588.89,95455.56,137334.41,142099.19,95684.62,27123.80,129096.72,212149.45,...,104999.18,122677.51,114432.59,123469.05,113533.50,117861.71,118718.78,96527.73,114107.88,77118.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16549,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16550,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,60.27,-60.27,0.00,0.00,0.00,0.00,0.00
16551,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16552,-1.14,-3.85,-0.13,-0.80,0.10,-2.26,-0.04,-1.02,-1.78,-0.01,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16553,-203.57,0.00,0.00,0.00,0.00,0.00,91.61,0.00,0.00,0.00,...,0.00,0.00,0.00,13.53,0.00,0.00,0.00,0.00,0.00,0.00

In [8]:
reg = linear_model.LinearRegression()
#reg.fit(df[['2015_Q1','2015_Q2','2015_Q3','2015_Q4','2016_Q1','2016_Q2','2016_Q3','2016_Q4','2017_Q1','2017_Q2','2017_Q3','2017_Q4','2018_Q1','2018_Q2','2018_Q3','2018_Q4','2019_Q1','2019_Q2','2019_Q3','2019_Q4','2020_Q1','2020_Q2','2020_Q3','2020_Q4','2021_Q1','2021_Q2','2021_Q3','2021_Q4','2022_Q1','2022_Q2']],df.'2022_Q3')
reg.fit(df[['MMXXII_Q1','MMXXII_Q2']],df.MMXXII_Q3)

LinearRegression()

In [9]:
reg.coef_

array([0.1145817 , 0.42832748])

In [10]:
reg.intercept_

240.64459162064452

In [11]:
reg.predict([[1738016.33,531366.33]])

array([426984.30467053])

In [12]:
0.1145817*1738016.33+0.42832748*531366.33+240.64459162064452

426984.31139653